import React, { useState } from 'react';
import { getProfs } from '../../utils/profStore';
import { cF, mHP } from '../../utils/character';
import BestiaryEditor from './BestiaryEditor';
import DonatePage from './DonatePage';
import GameView from '../GameView';
import GMRoll from './GMRoll';
import LoreEditor from './LoreEditor';
import ProfEditor from './ProfEditor';
import RaceEditor from './RaceEditor';
import ShopEditor from './ShopEditor';

function GMPanel(pr){var _s=useState(null);var sid=_s[0];var sS=_s[1];var _sl=useState(false);var sl=_sl[0];var sSL=_sl[1];
var showBest=pr.showBest||false;var sShowBest=pr.setShowBest||function(){};var _rv=useState(false);var rv=_rv[0];var sRV=_rv[1];var _sh=useState(false);var shp=_sh[0];var sShp=_sh[1];var _pe=useState(false);var pe=_pe[0];var sPE=_pe[1];
var sel=pr.characters.find(function(c){return c._fbId===sid});
if(sel)return <GameView char={sel} save={function(d){pr.saveChar(sel._fbId,d)}} onBack={function(){sS(null)}} isGM={true} logs={pr.logs} addLog={pr.addLog} lore={pr.lore} mapData={pr.mapData} saveMap={pr.saveMap} characters={pr.characters} spawned={pr.spawned} saveSpawned={pr.saveSpawned} pendAtk={pr.pendAtk} clearPendingAttack={pr.clearPendingAttack} room={pr.roomCode} savePendingAttack={pr.savePendingAttack} saveNpcHit={pr.saveNpcHit} shop={pr.shop} initiative={pr.initiative}/>;
if(sl)return(<div style={{flex:1,display:"flex",flexDirection:"column"}}><div style={{padding:"8px 10px",borderBottom:"2px solid #c084fc28",background:"#1f1330",display:"flex",alignItems:"center",gap:6}}><button onClick={function(){sSL(false)}} style={{background:"none",border:"none",fontSize:14,cursor:"pointer",color:"#a89a82"}}>←</button><span style={{fontFamily:"'Cinzel',serif",fontWeight:900,fontSize:14,color:"#7c3aed"}}>📚 Лорбук</span></div><div style={{flex:1,padding:8,overflowY:"auto"}}><LoreEditor lore={pr.lore} saveLore={pr.saveLore} mapData={pr.mapData} saveMap={pr.saveMap} characters={pr.characters}/></div></div>);
if(rv)return(<div style={{flex:1,padding:8,overflowY:"auto"}}><RaceEditor races={pr.races} saveRaces={pr.saveRaces} onBack={function(){sRV(false)}}/></div>);
if(pe)return(<div style={{flex:1,padding:8,overflowY:"auto"}}><ProfEditor profs={pr.profs} saveProfs={pr.saveProfs} onBack={function(){sPE(false)}}/></div>);
if(shp)return(<div style={{flex:1,padding:8,overflowY:"auto"}}><ShopEditor shop={pr.shop} saveShop={pr.saveShop} onBack={function(){sShp(false)}}/></div>);
if(showBest)return <BestiaryEditor npcTempl={pr.npcTempl} saveNpcTempl={pr.saveNpcTempl} spawned={pr.spawned} saveSpawned={pr.saveSpawned} onBack={function(){sShowBest(false)}} addLog={pr.addLog} characters={pr.characters} roomCode={pr.roomCode} savePendingAttack={pr.savePendingAttack} clearPendingAttack={pr.clearPendingAttack} pendAtk={pr.pendAtk} logs={pr.logs} initiative={pr.initiative} saveInitiative={pr.saveInitiative}/>;
return(<div style={{flex:1,display:"flex",flexDirection:"column"}}><div style={{padding:"8px 10px",borderBottom:"2px solid #c084fc28",background:"#1f1330"}}><div style={{fontFamily:"'Cinzel',serif",fontWeight:900,fontSize:16,color:"#7c3aed",textAlign:"center"}}>🎭 ГМ</div></div><div style={{flex:1,padding:8,overflowY:"auto",display:"flex",flexDirection:"column",gap:6}}>
<button onClick={function(){sSL(true)}} style={{width:"100%",padding:10,borderRadius:9,border:"2px solid #8b5cf630",background:"#1f1330",fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:13,color:"#7c3aed",cursor:"pointer"}}>📚 Лорбук</button>
<button onClick={function(){sShowBest(true)}} style={{width:"100%",padding:10,borderRadius:9,border:"2px solid #ef444430",background:"#2a1414",fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:13,color:"#ef4444",cursor:"pointer"}}>👹 Бестиарий / NPC</button>
<button onClick={function(){sRV(true)}} style={{width:"100%",padding:10,borderRadius:9,border:"2px solid #10b98140",background:"#0e2018",fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:13,color:"#34d399",cursor:"pointer"}}>🧬 Расы</button>
<button onClick={function(){sPE(true)}} style={{width:"100%",padding:10,borderRadius:9,border:"2px solid #a78bfa40",background:"#1f1330",fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:13,color:"#a78bfa",cursor:"pointer"}}>🎭 Классы</button>
<button onClick={function(){sShp(true)}} style={{width:"100%",padding:10,borderRadius:9,border:"2px solid #f59e0b40",background:"#2a2008",fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:13,color:"#f0b352",cursor:"pointer"}}>🛒 Магазин / Вещи</button>
<GMRoll addLog={pr.addLog}/>
{pr.characters.length===0&&<div style={{textAlign:"center",padding:20,color:"#a89a82"}}>Ожидаем...</div>}
{pr.characters.map(function(c){var inf=cF(c);var pf=getProfs().find(function(p){return p.id===c.profId})||getProfs()[0];var mx=c.hpOv||mHP(inf.fs);var ch=c.curHp!==null&&c.curHp!==undefined?c.curHp:mx;return(<div key={c._fbId} style={{background:"#1d1a14",border:"2px solid #c084fc18",borderRadius:9,padding:"7px 9px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:3}}><span style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:12}}>{c.name||"?"} <span style={{fontSize:8,color:"#a89a82"}}>{pf.name} Ур.{c.level}</span>{c.active&&<span style={{fontSize:7,background:"#10b981",color:"#fff",borderRadius:3,padding:"1px 4px",marginLeft:4}}>В ИГРЕ</span>}</span><div style={{display:"flex",gap:2}}><button onClick={function(){pr.saveChar(c._fbId,Object.assign({},c,{active:!c.active}))}} style={{padding:"3px 7px",borderRadius:5,border:"1px solid "+(c.active?"#10b98140":"#322d24"),background:c.active?"#0e2018":"#1d1a14",fontWeight:700,fontSize:8,color:c.active?"#34d399":"#a89a82",cursor:"pointer"}}>{c.active?"✓ Активен":"В игру"}</button><button onClick={function(){sS(c._fbId)}} style={{padding:"3px 8px",borderRadius:5,border:"1px solid #7c3aed28",background:"#1f1330",fontWeight:700,fontSize:9,color:"#7c3aed",cursor:"pointer"}}>Открыть</button></div></div>
<div style={{fontSize:9}}>{"❤️ "+ch+"/"+mx+" 🔥 "+(inf.fs.WILL||0)}</div>
<div style={{display:"flex",gap:2,marginTop:3,flexWrap:"wrap"}}><button onClick={function(){pr.saveChar(c._fbId,Object.assign({},c,{level:c.level+1,lvlPts:(c.lvlPts||0)+2}))}} style={{padding:"3px 6px",borderRadius:4,border:"1px solid #10b98128",background:"#0e2018",fontSize:8,fontWeight:700,color:"#34d399",cursor:"pointer"}}>⬆️+1</button><button onClick={function(){pr.saveChar(c._fbId,Object.assign({},c,{curHp:c.hpOv||mHP(cF(c).fs),curWill:c.willOv||cF(c).fs.WILL||1}))}} style={{padding:"3px 6px",borderRadius:4,border:"1px solid #10b98128",background:"#0e2018",fontSize:8,fontWeight:700,color:"#34d399",cursor:"pointer"}}>💤</button>{[-5,-1,1,5].map(function(d){return <button key={d} onClick={function(){var mx2=c.hpOv||mHP(cF(c).fs);var cur=c.curHp!==null&&c.curHp!==undefined?c.curHp:mx2;pr.saveChar(c._fbId,Object.assign({},c,{curHp:Math.max(0,Math.min(mx2,cur+d))}))}} style={{padding:"3px 5px",borderRadius:4,border:"1px solid #ef444420",background:d<0?"#2a1414":"#0e2018",fontSize:8,fontWeight:700,color:d<0?"#ef4444":"#10b981",cursor:"pointer"}}>{"HP"+(d>0?"+":"")+d}</button>})}<button onClick={function(){if(window.confirm("Удалить "+c.name+"?"))pr.deleteChar(c._fbId)}} style={{padding:"3px 6px",borderRadius:4,border:"1px solid #ef444440",background:"#2a1414",fontSize:8,fontWeight:700,color:"#ef4444",cursor:"pointer"}}>🗑️ Удалить</button></div></div>)})}
<div style={{border:"2px solid #322d24",borderRadius:9,padding:"7px 8px",background:"#1d1a14"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:4}}><span style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:12}}>📜 Общий лог</span><button onClick={function(){if(window.confirm("Очистить все логи?"))pr.clearLogs()}} style={{fontSize:8,background:"#2a1414",border:"1px solid #ef444420",borderRadius:4,padding:"2px 6px",cursor:"pointer",color:"#ef4444",fontWeight:700}}>🗑️ Очистить</button></div><div style={{maxHeight:250,overflowY:"auto",display:"flex",flexDirection:"column",gap:2}}>{(pr.logs||[]).length===0&&<div style={{textAlign:"center",padding:10,color:"#a89a82",fontStyle:"italic",fontSize:9}}>Пусто</div>}{(pr.logs||[]).map(function(l,i){var bgc=l.type==="magic_fail"?"#311717":l.type==="magic"?"#1f1330":l.type==="rest"?"#0e2018":l.type==="dodge"?"#0e2018":l.type==="zone"?"#231b08":l.type==="hit"?"#0e1a2b":l.type==="dmg_npc"?"#2a1414":l.type==="dmg"?"#2a1414":l.type==="spawn"?"#1f1330":"#1d1a14";return <div key={i} style={{background:bgc,border:"1px solid #322d2420",borderRadius:5,padding:"4px 6px",fontSize:9,animation:i===0?"slideIn 0.3s":"none"}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontWeight:700,color:"#ece5d8"}}>{l.who||"?"}</span>{l.ts&&<span style={{fontSize:7,color:"#c2b69e"}}>{new Date(l.ts).toLocaleTimeString()}</span>}</div><div style={{color:"#b3a890",marginTop:1}}>{l.label}</div>{l.detail&&<div style={{fontSize:8,color:"#9a8f7c",fontFamily:"monospace"}}>{l.detail}</div>}{l.total>0&&<div style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:13,color:l.type==="magic_fail"?"#dc2626":"#ece5d8"}}>{"= "+l.total}</div>}</div>})}</div></div>
</div></div>)}


/* ── DonatePage ── */

export default GMPanel;
