import React, { useState } from 'react';
import { getProfs } from '../../utils/profStore';
import { SD, SKD, skLabel } from '../../data/stats';
import { S } from '../../styles/ui';
import { cF, rndStats, uSP, uSkP } from '../../utils/character';
import { getRaces } from '../../utils/raceStore';
import { r1, sm, rollHit } from '../../utils/dice';
import ContactList from './ContactList';
import { RaceInfo, ProfInfo } from './CharInfo';

function CharTab(pr){var c=pr.char;var sv=pr.save;var oR=pr.onRoll;var gm=pr.isGM;var inf=cF(c);var rc=inf.race;var fs=inf.fs;var es=inf.eSk;var pf=getProfs().find(function(p){return p.id===c.profId})||getProfs()[0];var stL=40-uSP(c.stats||{});var bsk=rc.bsp?1:0;var skL=(60+bsk)-uSkP(c.skills||{});var _os=useState(null);var oSt=_os[0];var sOS=_os[1];var avL=(c.lvlPts||0)-(c.spentLvlPts||0);var _un=useState(null);var undo=_un[0];var sU=_un[1];
function uS(k,d){var stats=Object.assign({},c.stats);if(c.locked){if(d<0)return;if(avL<5)return;stats[k]=(stats[k]||0)+1;if(stats[k]>10)return;sv(Object.assign({},c,{stats:stats,spentLvlPts:(c.spentLvlPts||0)+5}));return}stats[k]=(stats[k]||0)+d;if(stats[k]<1||stats[k]>8)return;if(uSP(stats)>40)return;sv(Object.assign({},c,{stats:stats}))}
function uSk(n,d){var skills=Object.assign({},c.skills);if(c.locked){if(d<0)return;var sd=Object.values(SKD).flat().find(function(s){return s.name===n});var cost=sd&&sd.x2?4:2;if(avL<cost)return;skills[n]=(skills[n]||0)+1;if(skills[n]>10)return;sv(Object.assign({},c,{skills:skills,spentLvlPts:(c.spentLvlPts||0)+cost}));return}skills[n]=(skills[n]||0)+d;if(skills[n]<0||skills[n]>10)return;if(uSkP(skills)>60+bsk)return;sv(Object.assign({},c,{skills:skills}))}
return(<div style={{display:"flex",flexDirection:"column",gap:8}}>
<div style={{display:"flex",gap:4}}>{!c.locked&&<button onClick={function(){sU({name:c.name,raceId:c.raceId,humanBonusStat:c.humanBonusStat,stats:Object.assign({},c.stats),skills:Object.assign({},c.skills)});var r=rndStats(c.profId,c.raceId);sv(Object.assign({},c,r,{curHp:null,curWill:null}))}} style={{flex:1,padding:8,borderRadius:8,border:"2px solid #f59e0b40",background:"#2a2008",fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:12,color:"#f0b352",cursor:"pointer"}}>🎲 Рандом</button>}{!c.locked&&undo&&<button onClick={function(){sv(Object.assign({},c,undo,{curHp:null,curWill:null}));sU(null)}} style={{padding:"8px 12px",borderRadius:8,border:"2px solid #3b82f640",background:"#0e1a2b",fontWeight:700,fontSize:12,color:"#3b82f6",cursor:"pointer"}}>↩️</button>}<button onClick={function(){sv(Object.assign({},c,{locked:!c.locked}))}} style={{padding:"8px 12px",borderRadius:8,border:c.locked?"2px solid #ef444440":"2px solid #10b98140",background:c.locked?"#2a1414":"#0e2018",fontWeight:700,fontSize:12,cursor:"pointer",color:c.locked?"#ef4444":"#10b981",fontFamily:"'Cinzel',serif"}}>{c.locked?"🔒":"🔓"}</button></div>
{c.locked&&avL>0&&<div style={{background:"#231b08",border:"2px solid #f59e0b40",borderRadius:8,padding:"5px 8px",fontSize:10,fontWeight:700,color:"#f0b352"}}>{"⬆️ Очки: "+avL}</div>}
<div style={{display:"flex",gap:5,flexWrap:"wrap"}}><div style={{flex:2,minWidth:120}}><label style={S.lb}>Имя</label><input style={S.inp} value={c.name||""} disabled={c.locked&&!gm} onChange={function(e){sv(Object.assign({},c,{name:e.target.value}))}}/></div><div style={{flex:1,minWidth:50}}><label style={S.lb}>Ур.</label><input style={Object.assign({},S.inp,{background:"#262219"})} value={c.level} disabled/></div></div>
<div><label style={S.lb}>Раса</label><select value={c.raceId} disabled={c.locked&&!gm} onChange={function(e){sv(Object.assign({},c,{raceId:e.target.value,curHp:null}))}} style={Object.assign({},S.inp,{cursor:"pointer"})}>{getRaces().map(function(r){return <option key={r.id} value={r.id}>{r.name}</option>})}</select></div>
{rc.id!=="none"&&<RaceInfo race={rc}/>}
<div><label style={S.lb}>Профессия</label><select value={c.profId} disabled={c.locked&&!gm} onChange={function(e){sv(Object.assign({},c,{profId:e.target.value}))}} style={Object.assign({},S.inp,{cursor:"pointer"})}>{getProfs().map(function(p){return <option key={p.id} value={p.id}>{p.name}</option>})}</select></div>
{pf.id!=="none"&&<ProfInfo prof={pf} char={c} save={sv} finalStats={fs} finalSkills={es} onRoll={oR} addLog={pr.addLog}/>}
{!c.locked&&<div style={Object.assign({},S.bud,{background:stL===0?"#123424":"#0e1a2b",borderColor:stL===0?"#10b98140":"#3b82f640"})}><span style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:10}}>Статы</span><span style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:13,color:stL===0?"#10b981":"#3b82f6"}}>{stL+"/40"}</span></div>}
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(95px,1fr))",gap:3}}>{SD.map(function(st){var b=(c.stats||{})[st.key]||1;var e=fs[st.key];var rb=e-b;return(<div key={st.key} style={{background:st.color+"08",border:"2px solid "+st.color+"18",borderRadius:8,padding:"4px 2px",textAlign:"center"}}><div style={{fontSize:11}}>{st.emoji}<span style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:9,color:st.color,marginLeft:2}}>{st.key}</span></div><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:2}}><button onClick={function(){uS(st.key,-1)}} style={Object.assign({},S.sm,{width:18,height:18,fontSize:9})}>−</button><button onClick={function(){var R=rollHit();var d=R.d;var t=d+e;if(pr.addLog)pr.addLog({who:c.name||"???",type:"skill",label:"Бросок "+st.key+(R.crit?" 🌟КРИТ":R.fumble?" 💀ПРОВАЛ":""),detail:"🎲"+d+" + "+st.key+"("+e+") = "+t,total:t});oR({label:st.key,d10:d,crit:R.crit,fumble:R.fumble,parts:[{label:st.key,value:e}],total:t})}} style={{fontFamily:"'Cinzel',serif",fontSize:17,fontWeight:700,background:"none",border:"none",cursor:"pointer",color:"#fff"}}>{e}</button><button onClick={function(){uS(st.key,1)}} style={Object.assign({},S.sm,{width:18,height:18,fontSize:9,color:st.color})}>+</button></div>{rb!==0&&<div style={{fontSize:7,color:rb>0?"#059669":"#dc2626",fontWeight:700}}>{"("+b+(rb>0?"+":"")+rb+")"}</div>}</div>)})}</div>
{!c.locked&&<div style={Object.assign({},S.bud,{background:skL===0?"#123424":"#231b08",borderColor:skL===0?"#10b98140":"#f59e0b40"})}><span style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:10}}>Навыки</span><span style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:13,color:skL===0?"#10b981":"#d97706"}}>{skL+"/"+(60+bsk)}</span></div>}
{SD.map(function(st){var sks=SKD[st.key];if(!sks)return null;var op=oSt===st.key;return(<div key={st.key} style={{border:"1px solid "+st.color+"15",borderRadius:8,overflow:"hidden"}}><button onClick={function(){sOS(op?null:st.key)}} style={{width:"100%",display:"flex",justifyContent:"space-between",padding:"5px 8px",background:st.color+"06",border:"none",cursor:"pointer"}}><span style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:9,color:st.color}}>{st.emoji+" "+st.key}</span><span style={{fontSize:9,color:"#a89a82",transform:op?"rotate(180deg)":"none"}}>▼</span></button>{op&&<div style={{padding:"2px 5px 4px",display:"flex",flexDirection:"column",gap:1}}>{sks.map(function(sk){var ev=es[sk.name]||0;return(<div key={sk.name} style={{display:"flex",alignItems:"center",gap:2,padding:"2px 3px",borderRadius:4}}><button onClick={function(){var R=rollHit();var d=R.d;var sv2=fs[st.key];var t=d+sv2+ev;if(pr.addLog)pr.addLog({who:c.name||"???",type:"skill",label:"Бросок "+skLabel(sk.name)+(R.crit?" 🌟КРИТ":R.fumble?" 💀ПРОВАЛ":""),detail:"🎲"+d+" + "+st.key+"("+sv2+") + "+skLabel(sk.name)+"("+ev+") = "+t,total:t});oR({label:skLabel(sk.name),d10:d,crit:R.crit,fumble:R.fumble,parts:[{label:st.key,value:sv2},{label:skLabel(sk.name),value:ev}],total:t})}} style={{background:"none",border:"none",cursor:"pointer",fontSize:9,padding:0,opacity:ev>0?1:0.3}}>🎲</button><span style={{flex:1,fontSize:8,fontWeight:ev>0?700:400}}>{skLabel(sk.name)}{sk.x2&&<span style={{color:"#ef4444",fontSize:7}}>×2</span>}</span><span style={{fontSize:6,color:"#6b6356"}}>{"d10+"+fs[st.key]+"+"+ev}</span><button onClick={function(){uSk(sk.name,-1)}} style={Object.assign({},S.sm,{width:16,height:16,fontSize:7})}>−</button><span style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:11,minWidth:12,textAlign:"center",color:ev>0?st.color:"#4b443a"}}>{ev}</span><button onClick={function(){uSk(sk.name,1)}} style={Object.assign({},S.sm,{width:16,height:16,fontSize:7,color:st.color})}>+</button></div>)})}</div>}</div>)})}
<div style={{border:"2px solid #322d24",borderRadius:9,padding:8,background:"#1d1a14"}}><label style={S.lb}>📋 Профиль</label><div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:6,marginTop:4}}><label style={{width:180,height:180,borderRadius:10,background:c.portrait?"none":"linear-gradient(135deg,#322d24,#3a3322)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:c.portrait?0:48,flexShrink:0,border:"2px solid #3a3429",cursor:"pointer",overflow:"hidden",position:"relative"}}>{c.portrait?<img src={c.portrait} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<div style={{textAlign:"center"}}><div>{(c.name||"?")[0]}</div><div style={{fontSize:10,color:"#a89a82",marginTop:4}}>📷 Загрузить фото</div></div>}<input type="file" accept="image/*" style={{display:"none"}} onChange={function(e){var file=e.target.files&&e.target.files[0];if(!file)return;if(file.size>500000){alert("Файл слишком большой! Макс. 500KB");return}var reader=new FileReader();reader.onload=function(ev){sv(Object.assign({},c,{portrait:ev.target.result}))};reader.readAsDataURL(file)}}/></label>{c.portrait&&<button onClick={function(){sv(Object.assign({},c,{portrait:""}))}} style={{fontSize:9,background:"none",border:"none",color:"#ef4444",cursor:"pointer"}}>✕ Удалить фото</button>}</div><div style={{marginTop:3}}><label style={{fontSize:6,fontWeight:700,color:"#b3a890"}}>Био</label><textarea style={Object.assign({},S.inp,{minHeight:45,resize:"vertical",fontSize:9,padding:3})} value={c.bio||""} onChange={function(e){sv(Object.assign({},c,{bio:e.target.value}))}}/></div></div>
{["friends","enemies"].map(function(lk){var isF=lk==="friends";var items=c[lk]||[];return <ContactList key={lk} label={isF?"🤝 Друзья":"⚔️ Враги"} color={isF?"#10b981":"#ef4444"} bg={isF?"#0e2018":"#2a1414"} items={items} onChange={function(ni){sv(Object.assign({},c,function(){var o={};o[lk]=ni;return o}()))}}/>})}
</div>)}

/* ── ContactList ── */

export default CharTab;
