import React, { useState } from 'react';
import { getProfs } from '../../utils/profStore';
import { S } from '../../styles/ui';
import { cF, rndStats } from '../../utils/character';
import { getRaces } from '../../utils/raceStore';
import ContactList from './ContactList';
import { RaceInfo, ProfInfo } from './CharInfo';

function CharTab(pr){var c=pr.char;var sv=pr.save;var oR=pr.onRoll;var gm=pr.isGM;var inf=cF(c);var rc=inf.race;var fs=inf.fs;var es=inf.eSk;var pf=getProfs().find(function(p){return p.id===c.profId})||getProfs()[0];var avL=(c.lvlPts||0)-(c.spentLvlPts||0);var _un=useState(null);var undo=_un[0];var sU=_un[1];
return(<div style={{display:"flex",flexDirection:"column",gap:8}}>
<div style={{display:"flex",gap:4}}>{!c.locked&&<button onClick={function(){sU({name:c.name,raceId:c.raceId,humanBonusStat:c.humanBonusStat,stats:Object.assign({},c.stats),skills:Object.assign({},c.skills)});var r=rndStats(c.profId,c.raceId);sv(Object.assign({},c,r,{curHp:null,curWill:null}))}} style={{flex:1,padding:8,borderRadius:8,border:"2px solid #f59e0b40",background:"#2a2008",fontFamily:"'Inter',sans-serif",fontWeight:700,fontSize:12,color:"#f0b352",cursor:"pointer"}}>🎲 Рандом</button>}{!c.locked&&undo&&<button onClick={function(){sv(Object.assign({},c,undo,{curHp:null,curWill:null}));sU(null)}} style={{padding:"8px 12px",borderRadius:8,border:"2px solid #3b82f640",background:"#0e1a2b",fontWeight:700,fontSize:12,color:"#3b82f6",cursor:"pointer"}}>↩️</button>}<button onClick={function(){sv(Object.assign({},c,{locked:!c.locked}))}} style={{padding:"8px 12px",borderRadius:8,border:c.locked?"2px solid #ef444440":"2px solid #10b98140",background:c.locked?"#2a1414":"#0e2018",fontWeight:700,fontSize:12,cursor:"pointer",color:c.locked?"#ef4444":"#10b981",fontFamily:"'Inter',sans-serif"}}>{c.locked?"🔒":"🔓"}</button></div>
{c.locked&&avL>0&&<div style={{background:"#231b08",border:"2px solid #f59e0b40",borderRadius:8,padding:"5px 8px",fontSize:10,fontWeight:700,color:"#f0b352"}}>{"⬆️ Очки: "+avL}</div>}
<div style={{display:"flex",gap:5,flexWrap:"wrap"}}><div style={{flex:2,minWidth:120}}><label style={S.lb}>Имя</label><input style={S.inp} value={c.name||""} disabled={c.locked&&!gm} onChange={function(e){sv(Object.assign({},c,{name:e.target.value}))}}/></div><div style={{flex:1,minWidth:50}}><label style={S.lb}>Ур.</label><input style={Object.assign({},S.inp,{background:"#232532"})} value={c.level} disabled/></div></div>
<div><label style={S.lb}>Раса</label><select value={c.raceId} disabled={c.locked&&!gm} onChange={function(e){sv(Object.assign({},c,{raceId:e.target.value,curHp:null}))}} style={Object.assign({},S.inp,{cursor:"pointer"})}>{getRaces().map(function(r){return <option key={r.id} value={r.id}>{r.name}</option>})}</select></div>
{rc.id!=="none"&&<RaceInfo race={rc}/>}
<div><label style={S.lb}>Профессия</label><select value={c.profId} disabled={c.locked&&!gm} onChange={function(e){sv(Object.assign({},c,{profId:e.target.value}))}} style={Object.assign({},S.inp,{cursor:"pointer"})}>{getProfs().map(function(p){return <option key={p.id} value={p.id}>{p.name}</option>})}</select></div>
{pf.id!=="none"&&<ProfInfo prof={pf} char={c} save={sv} finalStats={fs} finalSkills={es} onRoll={oR} addLog={pr.addLog}/>}
<div style={{border:"2px solid #34374a",borderRadius:9,padding:8,background:"#1b1d29"}}><label style={S.lb}>📋 Профиль</label><div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:6,marginTop:4}}><label style={{width:180,height:180,borderRadius:10,background:c.portrait?"none":"linear-gradient(135deg,#34374a,#3a3322)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:c.portrait?0:48,flexShrink:0,border:"2px solid #34374a",cursor:"pointer",overflow:"hidden",position:"relative"}}>{c.portrait?<img src={c.portrait} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<div style={{textAlign:"center"}}><div>{(c.name||"?")[0]}</div><div style={{fontSize:10,color:"#9397ab",marginTop:4}}>📷 Загрузить фото</div></div>}<input type="file" accept="image/*" style={{display:"none"}} onChange={function(e){var file=e.target.files&&e.target.files[0];if(!file)return;if(file.size>500000){alert("Файл слишком большой! Макс. 500KB");return}var reader=new FileReader();reader.onload=function(ev){sv(Object.assign({},c,{portrait:ev.target.result}))};reader.readAsDataURL(file)}}/></label>{c.portrait&&<button onClick={function(){sv(Object.assign({},c,{portrait:""}))}} style={{fontSize:9,background:"none",border:"none",color:"#ef4444",cursor:"pointer"}}>✕ Удалить фото</button>}</div><div style={{marginTop:3}}><label style={{fontSize:6,fontWeight:700,color:"#9397ab"}}>Био</label><textarea style={Object.assign({},S.inp,{minHeight:45,resize:"vertical",fontSize:9,padding:3})} value={c.bio||""} onChange={function(e){sv(Object.assign({},c,{bio:e.target.value}))}}/></div></div>
{["friends","enemies"].map(function(lk){var isF=lk==="friends";var items=c[lk]||[];return <ContactList key={lk} label={isF?"🤝 Друзья":"⚔️ Враги"} color={isF?"#10b981":"#ef4444"} bg={isF?"#0e2018":"#2a1414"} items={items} onChange={function(ni){sv(Object.assign({},c,function(){var o={};o[lk]=ni;return o}()))}}/>})}
</div>)}

/* ── ContactList ── */

export default CharTab;
