import React, { useState } from 'react';
import { S } from '../../styles/ui';
import { uid } from '../../utils/dice';

function ContactList(pr){var _s=useState(false);var sa=_s[0];var sSA=_s[1];var _n=useState("");var cn=_n[0];var sCN=_n[1];var _r=useState("");var cr=_r[0];var sCR=_r[1];var _b=useState("");var cb=_b[0];var sCB=_b[1];var _re=useState("");var cre=_re[0];var sCRE=_re[1];var _ed=useState(null);var eid=_ed[0];var sEid=_ed[1];
function addC(){if(!cn.trim())return;if(eid){pr.onChange(pr.items.map(function(it){return it.id===eid?Object.assign({},it,{name:cn.trim(),race:cr.trim(),bio:cb.trim(),reason:cre.trim()}):it}));sEid(null)}else{pr.onChange(pr.items.concat([{id:uid(),name:cn.trim(),race:cr.trim(),bio:cb.trim(),reason:cre.trim()}]))}sCN("");sCR("");sCB("");sCRE("");sSA(false)}
function startEdit(it){sCN(it.name);sCR(it.race||"");sCB(it.bio||"");sCRE(it.reason||"");sEid(it.id);sSA(true)}
return(<div style={{border:"2px solid "+pr.color+"20",borderRadius:9,padding:"6px 8px",background:pr.bg+"60"}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:3}}><label style={Object.assign({},S.lb,{color:pr.color})}>{pr.label}</label><button onClick={function(){sSA(!sa);sEid(null);sCN("");sCR("");sCB("");sCRE("")}} style={{fontSize:8,background:"none",border:"none",cursor:"pointer",color:pr.color,fontWeight:700}}>{sa?"✕":"+ Добавить"}</button></div>
{sa&&<div style={{background:"#262219",borderRadius:6,padding:5,marginBottom:4,display:"flex",flexDirection:"column",gap:3,border:"1px solid #322d24"}}><div style={{display:"flex",gap:3}}><div style={{flex:2}}><label style={{fontSize:6,fontWeight:700,color:"#b3a890"}}>Имя</label><input style={Object.assign({},S.inp,{fontSize:9,padding:3})} value={cn} onChange={function(e){sCN(e.target.value)}}/></div><div style={{flex:1}}><label style={{fontSize:6,fontWeight:700,color:"#b3a890"}}>Раса</label><input style={Object.assign({},S.inp,{fontSize:9,padding:3})} value={cr} onChange={function(e){sCR(e.target.value)}}/></div></div><div><label style={{fontSize:6,fontWeight:700,color:"#b3a890"}}>Био</label><input style={Object.assign({},S.inp,{fontSize:9,padding:3})} value={cb} onChange={function(e){sCB(e.target.value)}}/></div><div><label style={{fontSize:6,fontWeight:700,color:"#b3a890"}}>Причина</label><input style={Object.assign({},S.inp,{fontSize:9,padding:3})} value={cre} onChange={function(e){sCRE(e.target.value)}}/></div><button onClick={addC} style={{padding:4,borderRadius:4,border:"none",background:pr.color,color:"#fff",fontWeight:700,fontSize:9,cursor:"pointer"}}>{eid?"Сохранить":"Добавить"}</button></div>}
{pr.items.length===0&&!sa&&<div style={{textAlign:"center",padding:6,color:"#a89a82",fontStyle:"italic",fontSize:8}}>Пусто</div>}
{pr.items.map(function(it){return <div key={it.id} style={{display:"flex",alignItems:"flex-start",gap:4,padding:"4px 5px",borderRadius:5,background:"#262219",marginBottom:2,border:"1px solid #322d24"}}><div style={{flex:1}}><div style={{fontSize:10,fontWeight:700}}>{it.name}{it.race&&<span style={{fontSize:8,color:"#a89a82",marginLeft:3}}>{it.race}</span>}</div>{it.bio&&<div style={{fontSize:8,color:"#9a8f7c"}}>{it.bio}</div>}{it.reason&&<div style={{fontSize:8,color:pr.color,fontStyle:"italic"}}>{it.reason}</div>}</div><button onClick={function(){startEdit(it)}} style={{background:"none",border:"none",fontSize:9,cursor:"pointer",color:"#3b82f6"}}>✏️</button><button onClick={function(){pr.onChange(pr.items.filter(function(x){return x.id!==it.id}))}} style={{background:"none",border:"none",fontSize:9,cursor:"pointer",color:"#ef4444"}}>✕</button></div>})}
</div>)}

/* ── CombatTab ── */

export default ContactList;
