import React, { useState } from 'react';
import { S } from '../../styles/ui';
import { sm, uid } from '../../utils/dice';
import MapView from './MapView';
import ShopPicker from '../ShopPicker';

function InvTab(pr){var c=pr.char;var sv=pr.save;var _a=useState("");var ni=_a[0];var sNI=_a[1];
return(<div style={{display:"flex",flexDirection:"column",gap:6}}><div style={{display:"flex",gap:3}}><input style={Object.assign({},S.inp,{flex:2})} value={ni} onChange={function(e){sNI(e.target.value)}} placeholder="Предмет..." onKeyDown={function(e){if(e.key==="Enter"&&ni.trim()){sv(Object.assign({},c,{inventory:(c.inventory||[]).concat([{id:uid(),name:ni.trim(),qty:1,equipped:false}])}));sNI("")}}}/><button onClick={function(){if(!ni.trim())return;sv(Object.assign({},c,{inventory:(c.inventory||[]).concat([{id:uid(),name:ni.trim(),qty:1,equipped:false}])}));sNI("")}} style={Object.assign({},S.ab,{background:"#10b981",color:"#fff",fontWeight:700,border:"none"})}>+</button></div>
<div style={{background:"#2a2008",borderRadius:8,padding:"5px 8px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:10}}>💰</span><div style={{display:"flex",alignItems:"center",gap:2}}>{[-10,-1].map(function(d){return <button key={d} onClick={function(){sv(Object.assign({},c,{gold:Math.max(0,(c.gold||0)+d)}))}} style={S.sm}>{d}</button>})}<span style={{fontFamily:"'Cinzel',serif",fontSize:14,fontWeight:700,color:"#d97706",minWidth:24,textAlign:"center"}}>{c.gold||0}</span>{[1,10].map(function(d){return <button key={d} onClick={function(){sv(Object.assign({},c,{gold:(c.gold||0)+d}))}} style={S.sm}>{"+"+d}</button>})}</div></div>
<ShopPicker color="#f59e0b" items={(pr.shop||[]).filter(function(i){return i.cat==="item"})} sub={function(it){return it.desc||""}} onPick={function(it){sv(Object.assign({},c,{inventory:(c.inventory||[]).concat([{id:uid(),name:it.name,qty:1,equipped:false}])}))}}/>
<ShopPicker color="#a78bfa" label="🔧 Взять инструменты" items={(pr.shop||[]).filter(function(i){return i.cat==="tool"})} sub={function(it){return "Починка снаряжения "+(it.dice||"1d4")}} onPick={function(it){sv(Object.assign({},c,{inventory:(c.inventory||[]).concat([{id:uid(),name:it.name,qty:1,equipped:false,tool:true,dice:it.dice||"1d4"}])}))}}/>
<ShopPicker color="#84cc16" label="🏹 Взять боеприпасы" items={(pr.shop||[]).filter(function(i){return i.cat==="ammo"})} sub={function(it){return "Снаряд: "+(it.ptype||"Стрела")}} onPick={function(it){var pt=it.ptype||"Стрела";var inv=(c.inventory||[]).slice();var ex=inv.find(function(i){return i.proj&&i.ptype===pt});if(ex){inv=inv.map(function(i){return i===ex?Object.assign({},i,{qty:(i.qty||0)+1}):i})}else{inv=inv.concat([{id:uid(),name:it.name,qty:1,equipped:false,proj:true,ptype:pt}])}sv(Object.assign({},c,{inventory:inv}))}}/>
{(c.inventory||[]).map(function(it,idx){return <div key={(it.id!=null?it.id:"i")+"_"+idx} style={{display:"flex",alignItems:"center",gap:3,background:it.equipped?"#12233a":"#1d1a14",border:"1px solid #322d24",borderRadius:5,padding:"3px 6px"}}><button onClick={function(){sv(Object.assign({},c,{inventory:(c.inventory||[]).map(function(i,j){return j===idx?Object.assign({},i,{equipped:!i.equipped}):i})}))}} style={{background:"none",border:"none",fontSize:11,cursor:"pointer"}}>{it.equipped?"🛡️":"📦"}</button><span style={{flex:1,fontSize:9}}>{it.name}</span><button onClick={function(){sv(Object.assign({},c,{inventory:(c.inventory||[]).map(function(i,j){return j===idx?Object.assign({},i,{qty:Math.max(0,i.qty-1)}):i}).filter(function(i){return i.qty>0})}))}} style={Object.assign({},S.sm,{width:16,height:16,fontSize:7})}>−</button><span style={{fontSize:9,fontWeight:700}}>{it.qty}</span><button onClick={function(){sv(Object.assign({},c,{inventory:(c.inventory||[]).map(function(i,j){return j===idx?Object.assign({},i,{qty:i.qty+1}):i})}))}} style={Object.assign({},S.sm,{width:16,height:16,fontSize:7})}>+</button><button onClick={function(){sv(Object.assign({},c,{inventory:(c.inventory||[]).filter(function(i,j){return j!==idx})}))}} style={{background:"none",border:"none",color:"#ef4444",fontSize:9,cursor:"pointer"}}>✕</button></div>})}
</div>)}

/* ── MapView ── */
var TOKEN_COLORS=["#ef4444","#f97316","#f59e0b","#eab308","#84cc16","#10b981","#06b6d4","#3b82f6","#6366f1","#8b5cf6","#ec4899","#ece5d8","#ffffff","#a16207","#0f766e","#7c3aed","#be185d","#b45309","#cabfa9","#dc2626"];

export default InvTab;
