import React, { useState } from 'react';
import { db, ref, set, get } from '../firebase';
import { CSS } from '../styles/globalCss';
import { genCode } from '../utils/dice';

function Lobby(pr){var _m=useState("menu"),md=_m[0],sM=_m[1];var _c=useState(""),cd=_c[0],sC=_c[1];var _n=useState(""),nm=_n[0],sN=_n[1];var _p=useState(""),ps=_p[0],sP=_p[1];var _e=useState(""),er=_e[0],sE=_e[1];var _l=useState(false),ld=_l[0],sL=_l[1];
var lb=function(c){return{width:"100%",padding:14,borderRadius:12,border:"2px solid "+c+"40",background:c+"10",fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:15,color:c,cursor:"pointer"}};
var li={width:"100%",padding:"10px 12px",border:"2px solid #322d24",borderRadius:8,fontSize:14,fontFamily:"'Nunito',sans-serif",background:"#1d1a14",outline:"none",textAlign:"center"};
return(<div style={{fontFamily:"'Nunito',sans-serif",color:"#ece5d8",background:"linear-gradient(180deg,#221e17,#14110c)",minHeight:"100vh",maxWidth:520,margin:"0 auto",display:"flex",flexDirection:"column",justifyContent:"center",padding:"20px 16px"}}><style>{CSS}</style><div style={{textAlign:"center",marginBottom:24}}><div style={{fontSize:28,fontFamily:"'Cinzel',serif",fontWeight:900,color:"#ece5d8"}}>✦ Nox Aeterna</div><div style={{fontSize:14,fontFamily:"'Cinzel',serif",color:"#a89a82",marginTop:4}}>Fantasy Companion</div></div>
{md==="menu"&&<div style={{display:"flex",flexDirection:"column",gap:10}}><button onClick={function(){sM("join");sE("")}} style={lb("#3b82f6")}>🎮 Войти в комнату</button><button onClick={function(){sM("create");sE("")}} style={lb("#10b981")}>🏰 Создать комнату (ГМ)</button><button onClick={function(){sM("gm");sE("")}} style={lb("#8b5cf6")}>🎭 Войти как ГМ</button></div>}
{md==="join"&&<div style={{display:"flex",flexDirection:"column",gap:10,background:"#262219",border:"2px solid #322d24",borderRadius:14,padding:"20px 16px"}}><div style={{fontFamily:"'Cinzel',serif",fontWeight:900,fontSize:17,textAlign:"center"}}>🎮 Войти</div><input style={li} value={cd} onChange={function(e){sC(e.target.value.toUpperCase())}} placeholder="Код комнаты" maxLength={6}/><input style={li} value={nm} onChange={function(e){sN(e.target.value)}} placeholder="Твоё имя"/>{er&&<div style={{color:"#ef4444",fontSize:11,textAlign:"center"}}>{er}</div>}<button onClick={function(){if(!cd.trim()||!nm.trim()){sE("Заполни все поля");return}sL(true);get(ref(db,"rooms/"+cd.trim())).then(function(s){sL(false);if(!s.exists()){sE("Не найдена");return}pr.onJoin(cd.trim(),nm.trim(),false)}).catch(function(e){sL(false);sE(e.message)})}} disabled={ld} style={lb("#3b82f6")}>{ld?"⏳...":"Войти"}</button><button onClick={function(){sM("menu")}} style={{background:"none",border:"none",color:"#a89a82",cursor:"pointer",fontSize:12}}>← Назад</button></div>}
{md==="create"&&<div style={{display:"flex",flexDirection:"column",gap:10,background:"#262219",border:"2px solid #322d24",borderRadius:14,padding:"20px 16px"}}><div style={{fontFamily:"'Cinzel',serif",fontWeight:900,fontSize:17,textAlign:"center"}}>🏰 Создать</div><input style={li} type="password" value={ps} onChange={function(e){sP(e.target.value)}} placeholder="Пароль ГМ"/>{er&&<div style={{color:"#ef4444",fontSize:11,textAlign:"center"}}>{er}</div>}<button onClick={function(){if(!ps.trim()){sE("Введи пароль");return}sL(true);var rc=genCode();set(ref(db,"rooms/"+rc),{gmPassword:ps.trim(),created:new Date().toISOString()}).then(function(){sL(false);pr.onJoin(rc,null,true)}).catch(function(e){sL(false);sE(e.message)})}} disabled={ld} style={lb("#10b981")}>{ld?"⏳...":"Создать"}</button><button onClick={function(){sM("menu")}} style={{background:"none",border:"none",color:"#a89a82",cursor:"pointer",fontSize:12}}>← Назад</button></div>}
{md==="gm"&&<div style={{display:"flex",flexDirection:"column",gap:10,background:"#262219",border:"2px solid #322d24",borderRadius:14,padding:"20px 16px"}}><div style={{fontFamily:"'Cinzel',serif",fontWeight:900,fontSize:17,textAlign:"center"}}>🎭 ГМ</div><input style={li} value={cd} onChange={function(e){sC(e.target.value.toUpperCase())}} placeholder="Код комнаты" maxLength={6}/><input style={li} type="password" value={ps} onChange={function(e){sP(e.target.value)}} placeholder="Пароль ГМ"/>{er&&<div style={{color:"#ef4444",fontSize:11,textAlign:"center"}}>{er}</div>}<button onClick={function(){if(!cd.trim()||!ps.trim()){sE("Заполни");return}sL(true);get(ref(db,"rooms/"+cd.trim())).then(function(s){sL(false);if(!s.exists()){sE("Не найдена");return}if(s.val().gmPassword!==ps.trim()){sE("Неверный пароль");return}pr.onJoin(cd.trim(),null,true)}).catch(function(e){sL(false);sE(e.message)})}} disabled={ld} style={lb("#8b5cf6")}>{ld?"⏳...":"Войти"}</button><button onClick={function(){sM("menu")}} style={{background:"none",border:"none",color:"#a89a82",cursor:"pointer",fontSize:12}}>← Назад</button></div>}
</div>)}

export default Lobby;
